services:    
  dash_server:
    build: .
    restart: always
    ports:
      - "1995:1995"
    volumes:
      - ./:./
    command: ["gunicorn", "server:server", "--reload", "--bind", "0.0.0.0:1995"]
  # app_1:
  #   build: ./app_1
  #   ports:
  #     - "8001:8001"
  #   volumes:
  #     - ./app_1:/app
  # app_2:
  #   build: ./app_2
  #   ports:
  #     - "8002:8002"
  #   volumes:
  #     - ./app_2:/app